race_name: Western States
race_loc: Olympic Valley, CA
race_dist: 100M
race_ids:
  2015: 30033
  2016: 24773
  2017: 41765
  2018: 51243
  2019: 61359
  2020: 71208
  2021: 79446
  2022: 87878
  2023: 97204
  2024: 108752
  2025: 119682