dates:
  2022: December 9th, 2022
  2023: December 8th, 2023
  2024: December 6th, 2024
race_dist: 100M
race_id: 25273
race_loc: "Chiang Mai Province, Thailand"
race_name: Doi Inthanon Thailand 100M
race_uris:
  2022: 25273.doiinthanonbyutmbtrans-int160
  2023: 25273.doiinthanonbyutmbtrans-int160
  2024: 25273.doiinthanonbyutmbtrans-int160