dates:
  2021: 2021-10-22
  2022: 2022-10-21
  2023: 2023-10-20
  2024: 2024-10-18
  2025: 2025-10-17
race_dist: 100K
race_id: 623
race_loc: "Millau, France"
race_name: Festival des Templiers 100K
race_uris:
  2021: 623.festivaldestempliersendurancetrail
  2022: 623.festivaldestempliersendurancetrail
  2023: 623.festivaldestempliersendurancetrail
  2024: 623.festivaldestempliersendurancetrail
  2025: 623.festivaldestempliersendurancetrail